RWA-643 & RWA-646: Implement initiation job and mapping
hmcts/wa-task-monitor pull request #20
Opened 2021-08-04 14:19 UTC by alexbaeza

### JIRA link (if applicable) ###

### Change description ###

RWA-643 & RWA-646: Implement initiation job and mapping

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2021-08-12 08:50 UTC, indvamshi approved these changes

2021-08-12 08:52 UTC, alexbaeza commented on src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/initiation/InitiationJobService.java
> +            "1000",
at the moment we've decided to limit to a max of 1000 at a time to avoid any potential issues as it takes a while to process them.

2021-08-17 13:28 UTC, BenNzewi commented on src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/initiation/InitiationJobServiceTest.java
> +        assertQueryTargetsUserTasksAndNotDelayedTasks(getExpectedQueryParameters());
can we also assert the taskState is "unconfigured"?

2021-08-23 15:34 UTC, indvamshi requested changes

2021-08-23 15:34 UTC, indvamshi commented on src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/configuration/ConfigurationJobService.java
>                  log.info("Error while configuring task with id: '{}'", task.getId());
log it as error.

2021-08-23 15:35 UTC, alexbaeza commented on src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/configuration/ConfigurationJobService.java
>                  log.info("Error while configuring task with id: '{}'", task.getId());
```suggestion
                log.error("Error while configuring task with id: '{}'", task.getId());
```

2021-08-23 15:37 UTC, indvamshi approved these changes

2021-08-24 08:32 UTC, merged